accounting_adapter:
   GrantNorthccountAdapter
accounting_module:
   grantnorthaccounting.externalsystem.adapter


inventory_adapter:
   InventoryAdapter

inventory_module:
   inventory.adapter


strategy_name:
   SalesPricingStrategy
strategy_module:
   sales.Strategy.AbsoluteDiscountOverThreshold



proxy_name:
   Proxy
proxy_moudle:
   sales.proxy.sales_proxy
source_name:
   - TaxAdapter
   - GoldTaxProAdapter
source_module:
   sales.proxy.adapter


facade_name:
    Product
facade_module:
   inventory.InventoryFacade.inventory

composit_name:
   BestForStore
   # CompositPricingStrategy
composit_module:
   # sales.composit.bestforcustomer
   sales.composit.bestforstore
   # sales.composit.composit
strategy_name:
   - SalesPricingStrategy,sales.composit.AbsoluteDiscountOverThreshold
   - SalesPricingStrategy,sales.composit.PercentDisCountPricingStrategy

   
